/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Walmart;

/**
 *
 * @author Banny Juanda
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class AdminPage extends javax.swing.JFrame {
    public java.sql.Statement st;
    public String sql;
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Kode = new javax.swing.JTextField();
        txt_NamaB = new javax.swing.JTextField();
        txt_Jumlah = new javax.swing.JTextField();
        txt_Harga = new javax.swing.JTextField();
        txt_Kategori = new javax.swing.JTextField();
        btn_Simpan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 0, 18)); // NOI18N
        jLabel1.setText("TAMBAH DATA BARANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 58, -1, -1));

        jLabel2.setText("Kode Barang :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 119, 89, -1));

        jLabel3.setText("Nama Barang :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 153, 89, -1));

        jLabel4.setText("Jumlah Barang :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 187, 89, -1));

        jLabel6.setText("Harga Barang (Satuan) :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 221, 128, -1));

        txt_Kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KodeActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 116, 191, -1));
        getContentPane().add(txt_NamaB, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 153, 191, -1));
        getContentPane().add(txt_Jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 184, 191, -1));

        txt_Harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_HargaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 218, 191, -1));
        getContentPane().add(txt_Kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 258, 191, -1));

        btn_Simpan.setText("Simpan");
        btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, -1, -1));

        jLabel9.setText("Kategori Barang :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 261, 98, -1));

        btn_Exit.setText("Back");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SimpanActionPerformed
        // TODO add your handling code here:
        try {
        Connection conn = koneksi.koneksiDB();

        // Check if the record with the given code already exists
        String checkSql = "SELECT * FROM `barang` WHERE `kode_barang` = ?";
        try (PreparedStatement checkStatement = conn.prepareStatement(checkSql)) {
            checkStatement.setString(1, txt_Kode.getText());
            ResultSet resultSet = checkStatement.executeQuery();

            if (resultSet.next()) {
                // If record exists, perform an update
                String updateSql = "UPDATE `barang` SET `nama_barang`=?, `stock_barang`=?, `harga_barang`=?, `kategori_barang`=? WHERE `kode_barang`=?";
                try (PreparedStatement updateStatement = conn.prepareStatement(updateSql)) {
                    updateStatement.setString(1, txt_NamaB.getText());
                    updateStatement.setString(2, txt_Jumlah.getText());
                    updateStatement.setString(3, txt_Harga.getText());
                    updateStatement.setString(4, txt_Kategori.getText());
                    updateStatement.setString(5, txt_Kode.getText());
                    updateStatement.executeUpdate();
                }
                JOptionPane.showMessageDialog(rootPane, "Barang berhasil diupdate!");
            } else {
                // If record does not exist, perform an insert
                String insertSql = "INSERT INTO `barang` (`kode_barang`, `nama_barang`, `stock_barang`, `harga_barang`, `kategori_barang`) VALUES (?, ?, ?, ?, ?)";
                try (PreparedStatement insertStatement = conn.prepareStatement(insertSql)) {
                    insertStatement.setString(1, txt_Kode.getText());
                    insertStatement.setString(2, txt_NamaB.getText());
                    insertStatement.setString(3, txt_Jumlah.getText());
                    insertStatement.setString(4, txt_Harga.getText());
                    insertStatement.setString(5, txt_Kategori.getText());
                    insertStatement.executeUpdate();
                }
                JOptionPane.showMessageDialog(rootPane, "Barang berhasil ditambahkan!");
            }
        }
        txt_Kode.setText("");
        txt_NamaB.setText("");
        txt_Jumlah.setText("");
        txt_Harga.setText("");
        txt_Kategori.setText("");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btn_SimpanActionPerformed

    private void txt_HargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_HargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_HargaActionPerformed

    private void txt_KodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KodeActionPerformed
        // TODO add your handling code here:
        if(txt_Kode.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kode Barang Tidak Boleh Kosong!!!");
        }else{
            try{
                Connection conn = koneksi.koneksiDB();
                st = conn.createStatement();
                ResultSet rs = st.executeQuery("Select nama_barang, stock_barang, harga_barang, kategori_barang From barang Where kode_barang Like '%" +txt_Kode.getText()+ "%'");
                if(rs.next()){
                    txt_NamaB.setText(rs.getString("nama_barang"));
                    txt_Jumlah.setText(rs.getString("stock_barang"));
                    txt_Harga.setText(rs.getString("harga_barang"));
                    txt_Kategori.setText(rs.getString("kategori_barang"));
                }
            }catch(Exception e){
                System.out.println("Error");
            }
        }
    }//GEN-LAST:event_txt_KodeActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        // TODO add your handling code here:
        dispose();
        MenuAdmin menu = new MenuAdmin();
        menu.show();
    }//GEN-LAST:event_btn_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Jumlah;
    private javax.swing.JTextField txt_Kategori;
    private javax.swing.JTextField txt_Kode;
    private javax.swing.JTextField txt_NamaB;
    // End of variables declaration//GEN-END:variables
}
