/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Walmart;

/**
 *
 * @author Banny Juanda
 */

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class ListBarangPage extends javax.swing.JFrame {
    private DefaultTableModel tbModel;
    /**
     * Creates new form ListBarangPage
     */
    
    public void loadData(){
        tbModel.getDataVector().removeAllElements();
        tbModel.fireTableDataChanged();
        
        try{
            Connection conn = koneksi.koneksiDB();
            Statement st = conn.createStatement();
            
            String sql = "Select `kode_barang`, `nama_barang`, `stock_barang`, `harga_barang`, `kategori_barang` From barang";
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                Object[] obj = new Object[5];
                obj [0] = rs.getString("kode_barang");
                obj [1] = rs.getString("nama_barang");
                obj [2] = rs.getString("stock_barang");
                obj [3] = rs.getString("harga_barang");
                obj [4] = rs.getString("kategori_barang");
                
                
                tbModel.addRow(obj);
            }
            rs.close();
            st.close();
        }catch(Exception e){
            System.out.println("Terjadi Kesalahan!");
        }
    }
    
    public void cari(){
        DefaultTableModel tblModel = new DefaultTableModel();
        
        tblModel.addColumn("Kode Barang");
        tblModel.addColumn("Nama Barang");
        tblModel.addColumn("Stock Barang");
        tblModel.addColumn("Harga Barang");
        tblModel.addColumn("Kategori Barang");
        
        try{
            Connection con = koneksi.koneksiDB();
            String sql = "Select `kode_barang`, `nama_barang`, `stock_barang`, `harga_barang`, `kategori_barang` from barang Where kode_barang Like '%" +txt_Cari.getText()+ "%'" +
                    "Or nama_barang Like '%" +txt_Cari.getText()+"%'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()){
                tblModel.addRow(new Object[]{
                        rs.getString("kode_barang"),
                        rs.getString("nama_barang"),
                        rs.getString("stock_barang"),
                        rs.getString("harga_barang"),
                        rs.getString("kategori_barang"),
                });
                tbl_Detail.setModel(tblModel);
                loadData();
            }
            
        }catch(Exception e){
            System.out.println("");
        }finally{
            
        }
    }
    
    public ListBarangPage() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
        tbModel = new DefaultTableModel();
        tbl_Detail.setModel(tbModel);
        
        tbModel.addColumn("Kode Barang");
        tbModel.addColumn("Nama Barang");
        tbModel.addColumn("Stock Barang");
        tbModel.addColumn("Harga Barang");
        tbModel.addColumn("Kategori Barang");
        
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Detail = new javax.swing.JTable();
        btn_Batal = new javax.swing.JButton();
        btn_Pilih = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("LIST BARANG");

        jLabel2.setText("Cari :");

        txt_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CariActionPerformed(evt);
            }
        });
        txt_Cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_CariKeyTyped(evt);
            }
        });

        tbl_Detail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Detail);

        btn_Batal.setText("Batal");
        btn_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BatalActionPerformed(evt);
            }
        });

        btn_Pilih.setText("Pilih");
        btn_Pilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PilihActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(532, 532, 532)
                .addComponent(btn_Pilih)
                .addGap(18, 18, 18)
                .addComponent(btn_Batal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(txt_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Pilih)
                    .addComponent(btn_Batal)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_PilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PilihActionPerformed
        // TODO add your handling code here:
        int i = tbl_Detail.getSelectedRow();
        
        String kode = tbl_Detail.getValueAt(i, 0).toString();
        String nama = tbl_Detail.getValueAt(i, 1).toString();
        String harga = tbl_Detail.getValueAt(i, 3).toString();
        
        TransaksiPage.txt_Kode.setText(kode);
        TransaksiPage.txt_NamaB.setText(nama);
        TransaksiPage.txt_Harga.setText(harga);
        
        dispose();
    }//GEN-LAST:event_btn_PilihActionPerformed

    private void btn_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BatalActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_BatalActionPerformed

    private void txt_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CariActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txt_CariActionPerformed

    private void txt_CariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_CariKeyTyped
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txt_CariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListBarangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListBarangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListBarangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListBarangPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListBarangPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Batal;
    private javax.swing.JButton btn_Pilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Detail;
    private javax.swing.JTextField txt_Cari;
    // End of variables declaration//GEN-END:variables
}
