/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Walmart;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Banny Juanda
 */
public class RegisterPage extends javax.swing.JFrame {
    public java.sql.Statement st;
    public String sql;

    /**
     * Creates new form RegisterPage
     */
    public RegisterPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Username_037 = new javax.swing.JTextField();
        txt_Name_080 = new javax.swing.JTextField();
        txt_Password_037 = new javax.swing.JPasswordField();
        btn_Regis_080 = new javax.swing.JButton();
        btn_clr_080 = new javax.swing.JButton();
        btn_back_037 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_level_037 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 0, 24)); // NOI18N
        jLabel1.setText("REGISTRASI");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 51, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Username :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 15, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Name       :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Password :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        txt_Username_037.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Username_037ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(txt_Username_037, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        getContentPane().add(txt_Name_080, gridBagConstraints);

        txt_Password_037.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Password_037ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        getContentPane().add(txt_Password_037, gridBagConstraints);

        btn_Regis_080.setText("Register");
        btn_Regis_080.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Regis_080ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        getContentPane().add(btn_Regis_080, gridBagConstraints);

        btn_clr_080.setText("Clear");
        btn_clr_080.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clr_080ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 66, 6, 0);
        getContentPane().add(btn_clr_080, gridBagConstraints);

        btn_back_037.setText("Back");
        btn_back_037.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_037ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(51, 12, 6, 6);
        getContentPane().add(btn_back_037, gridBagConstraints);

        jLabel5.setText(" Level       :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(9, 15, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 112;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(txt_level_037, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Regis_080ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Regis_080ActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = koneksi.koneksiDB();
            sql = "INSERT INTO `user` (`username`, `nama`, `password`, `level`) VALUES ('"+txt_Username_037.getText()+"','"+txt_Name_080.getText()+"','"+txt_Password_037.getText()+"', '"+txt_level_037.getText()+"')";
            st = conn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(rootPane, "Akun Berhasil Di Registrasikan!");
            txt_Username_037.setText("");
            txt_Name_080.setText("");
            txt_Password_037.setText("");
            txt_level_037.setText("");
        }catch (Exception e){
            JOptionPane.showMessageDialog(rootPane, "Gagal Registrasi"+ e);
        }
    }//GEN-LAST:event_btn_Regis_080ActionPerformed

    private void btn_clr_080ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clr_080ActionPerformed
        // TODO add your handling code here:
        txt_Username_037.setText(null);
        txt_Name_080.setText(null);
        txt_Password_037.setText(null);
    }//GEN-LAST:event_btn_clr_080ActionPerformed

    private void btn_back_037ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_037ActionPerformed
        // TODO add your handling code here:
        try{
            dispose();
            LoginPage login = new LoginPage();
            login.show();
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btn_back_037ActionPerformed

    private void txt_Password_037ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Password_037ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Password_037ActionPerformed

    private void txt_Username_037ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Username_037ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Username_037ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Regis_080;
    private javax.swing.JButton btn_back_037;
    private javax.swing.JButton btn_clr_080;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_Name_080;
    private javax.swing.JPasswordField txt_Password_037;
    private javax.swing.JTextField txt_Username_037;
    private javax.swing.JTextField txt_level_037;
    // End of variables declaration//GEN-END:variables
}
