/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Walmart;

/**
 *
 * @author Banny Juanda
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TransaksiPage extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
    /**
     * Creates new form TransaksiPage
     */
    
    public void totalBiaya(){
        int jumlahBaris = tbl_Rinci.getRowCount();
        double totalBiaya = 0;
        double jumlahBarang, hargaBarang;
        for(int i = 0; i < jumlahBaris; i++){
            jumlahBarang = Integer.parseInt(tbl_Rinci.getValueAt(i, 2).toString());
            hargaBarang = Integer.parseInt(tbl_Rinci.getValueAt(i, 3).toString());
            totalBiaya = totalBiaya + (jumlahBarang * hargaBarang);
        }
        
        if(totalBiaya > 50000){
            double diskon = 0.1;
            totalBiaya = totalBiaya - (totalBiaya * diskon);
        }
        
        txt_Total.setText(String.valueOf(totalBiaya));
        txt_Display.setText(String.valueOf("Rp. "+totalBiaya));
    }
    
    public void loadData(){
        DefaultTableModel tbl = (DefaultTableModel) tbl_Rinci.getModel();
        tbl.addRow(new Object[]{
            txt_Kode.getText(),
            txt_NamaB.getText(),
            txt_Harga.getText(),
            txt_Jumlah.getText(),
            txt_Metode.getText(),
            txt_Total.getText()
        });
    }
    
    public void kosong(){
        DefaultTableModel tbl = (DefaultTableModel) tbl_Rinci.getModel();
        
        while(tbl.getRowCount() > 0){
            tbl.removeRow(0);
        }
    }
    
    public void clear(){
        txt_Total.setText("0");
        txt_Bayar.setText("0");
        txt_Kembalian.setText("0");
        txt_Display.setText("0");
        
    }
    
    public void clear2(){
        txt_Kode.setText("");
        txt_NamaB.setText("");
        txt_Harga.setText("");
        txt_Jumlah.setText("");
        txt_Metode.setText("");
    }
    
    public void tambahTransaksi(){
        double jumlah, harga, total;
        
        jumlah = Double.valueOf(txt_Jumlah.getText());
        harga = Double.valueOf(txt_Harga.getText());
        total = jumlah * harga;
        
        txt_Total.setText(String.valueOf(total));
        
        loadData();
        totalBiaya();
        clear2();
        txt_Kode.requestFocus();
    }
    
    public TransaksiPage() {
        initComponents();
        
        tblModel = new DefaultTableModel();
        
        tbl_Rinci.setModel(tblModel);
        
        tblModel.addColumn("Kode Barang");
        tblModel.addColumn("Nama Barang");
        tblModel.addColumn("Harga");
        tblModel.addColumn("Jumlah");
        tblModel.addColumn("Metode");
        tblModel.addColumn("Total");
        
        txt_Total.setText("0");
        txt_Bayar.setText("0");
        txt_Kembalian.setText("0");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Kode = new javax.swing.JTextField();
        txt_NamaB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Harga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Rinci = new javax.swing.JTable();
        btn_Tambah = new javax.swing.JButton();
        btn_Hapus = new javax.swing.JButton();
        btn_Bayar = new javax.swing.JButton();
        txt_Display = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_Total = new javax.swing.JTextField();
        txt_Bayar = new javax.swing.JTextField();
        txt_Kembalian = new javax.swing.JTextField();
        btn_Cari = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txt_Metode = new javax.swing.JTextField();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 0, 18)); // NOI18N
        jLabel1.setText("Transaksi");

        jLabel2.setText("Kode Barang");

        jLabel3.setText("Nama Barang");

        txt_Kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_KodeActionPerformed(evt);
            }
        });

        txt_NamaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamaBActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah");

        txt_Jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_JumlahActionPerformed(evt);
            }
        });

        tbl_Rinci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Rinci);

        btn_Tambah.setText("Tambah");
        btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TambahActionPerformed(evt);
            }
        });

        btn_Hapus.setText("Hapus");
        btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HapusActionPerformed(evt);
            }
        });

        btn_Bayar.setText("Bayar");
        btn_Bayar.setEnabled(false);
        btn_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BayarActionPerformed(evt);
            }
        });

        txt_Display.setEditable(false);
        txt_Display.setFont(new java.awt.Font("Uni Sans Heavy CAPS", 0, 18)); // NOI18N
        txt_Display.setText("RP. 0");

        jLabel6.setText("Total Bayar :");

        jLabel7.setText("Bayar :");

        jLabel8.setText("Kembalian :");

        txt_Total.setEditable(false);

        txt_Bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BayarActionPerformed(evt);
            }
        });

        txt_Kembalian.setEditable(false);

        btn_Cari.setText("Cari");
        btn_Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CariActionPerformed(evt);
            }
        });

        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel9.setText("Metode");

        btn_exit.setText("Exit");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_Kode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btn_Cari, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(txt_NamaB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Metode))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel3)
                                        .addGap(95, 95, 95)
                                        .addComponent(jLabel4)
                                        .addGap(135, 135, 135)
                                        .addComponent(jLabel5)
                                        .addGap(131, 131, 131)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8))
                                                .addGap(22, 22, 22)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_Bayar)
                                                    .addComponent(txt_Kembalian)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 27, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(283, 283, 283)
                        .addComponent(btn_exit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_exit)
                            .addComponent(btn_back))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)))))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Cari)
                    .addComponent(txt_NamaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_Metode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(txt_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_JumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_JumlahActionPerformed
        // TODO add your handling code here:
        tambahTransaksi();
    }//GEN-LAST:event_txt_JumlahActionPerformed

    private void btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TambahActionPerformed
        // TODO add your handling code here:
        tambahTransaksi();
        
        if(txt_Kode.getText().equals(txt_Kode.getText())){
            btn_Bayar.setEnabled(true);
        }
    }//GEN-LAST:event_btn_TambahActionPerformed

    private void btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)tbl_Rinci.getModel();
        int row = tbl_Rinci.getSelectedRow();
        tblModel.removeRow(row);
        totalBiaya();
        txt_Bayar.setText("0");
        txt_Kembalian.setText("0");
        if(txt_Kode.getText().equals("")){
            btn_Bayar.setEnabled(false);
        }
    }//GEN-LAST:event_btn_HapusActionPerformed

    private void txt_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BayarActionPerformed
        // TODO add your handling code here:
        double total, bayar, kembalian;
        
        total = Double.valueOf(txt_Total.getText());
        bayar = Double.valueOf(txt_Bayar.getText());
          
        if(total > bayar){
            JOptionPane.showMessageDialog(null, "Uang Tidak Cukup!");
        }else{
            kembalian = bayar - total;
            txt_Kembalian.setText(String.valueOf(kembalian));
        }
    }//GEN-LAST:event_txt_BayarActionPerformed

    private void btn_BayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BayarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel) tbl_Rinci.getModel();
        
        try{
            Connection conn = koneksi.koneksiDB();
            int baris = tbl_Rinci.getRowCount();
            
            for(int i = 0; i < baris; i++){
                String sql = "INSERT INTO transaksi(kode_barang, nama_barang, harga_barang, jumlah_barang, metode, total_harga) "
                        + "VALUES('"+tbl_Rinci.getValueAt(i,0)+"', '"+tbl_Rinci.getValueAt(i, 1)+"', '"+tbl_Rinci.getValueAt(i, 2)+"', '"+tbl_Rinci.getValueAt(i, 3) +"', '"+tbl_Rinci.getValueAt(i, 4)+"', '"+tbl_Rinci.getValueAt(i, 5)+"')";
                PreparedStatement ps = conn.prepareStatement(sql);
                ps.executeUpdate();
                ps.close();
            }
            
            JOptionPane.showMessageDialog(rootPane, "Transaksi Selesai. Terima Kasih");
        }catch(Exception e){
            System.out.println("Pembayaran Error!");
        }
        
        clear();
        kosong();
        txt_Display.setText("Rp. 0");
    }//GEN-LAST:event_btn_BayarActionPerformed

    private void btn_CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CariActionPerformed
        // TODO add your handling code here:
        ListBarangPage lb = new ListBarangPage();
        lb.setVisible(true);
    }//GEN-LAST:event_btn_CariActionPerformed

    private void txt_KodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_KodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_KodeActionPerformed

    private void txt_NamaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamaBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NamaBActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage login = new LoginPage();
        login.show();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Bayar;
    private javax.swing.JButton btn_Cari;
    private javax.swing.JButton btn_Hapus;
    private javax.swing.JButton btn_Tambah;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Rinci;
    private javax.swing.JTextField txt_Bayar;
    private javax.swing.JTextField txt_Display;
    public static javax.swing.JTextField txt_Harga;
    private javax.swing.JTextField txt_Jumlah;
    private javax.swing.JTextField txt_Kembalian;
    public static javax.swing.JTextField txt_Kode;
    private javax.swing.JTextField txt_Metode;
    public static javax.swing.JTextField txt_NamaB;
    private javax.swing.JTextField txt_Total;
    // End of variables declaration//GEN-END:variables
}
